env:
  browser: true
  commonjs: true
  es6: true
globals:
  angular: false
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
  no-unused-vars:
    - error
    - argsIgnorePattern: '^_'
      